# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: GitHub Field Day
description: > # this means to ignore newlines until "baseurl:"
  An unconference for leaders of technical student communities. 18th of November at Monzo HQ.
date: 2017-11-18T09:00:00.000Z
url: "http://githubfieldday.com" # the base hostname & protocol for your site
github_repo: https://github.com/githubfieldday/london2017
exclude: [
  'node_modules',
  'gulpfile.babel.js',
  'package-lock.json',
  'package.json',
  'README.md'
]
baseurl: '/london2017'

faqs:
  - q: Who can attend Field Day?
    a: Field Day is for student leaders of technical communities based in London. Most attendees will be undergraduate students.
  - q: What's a student leader?
    a: A student leader is someone who's actively involved in improving their local technical community. They might be the president or chairperson of their school's tech club or be one of the organizers of the annual hackathon. They might run the student hardware group or be actively involved in introducing other students to programming.
  - q: What's an unconference?
    a: A loosely structured conference emphasizing the informal exchange of information and ideas between participants (to quote the Google definition). Most content at Field Day will be in the form of lightning talks and discussions conducted by attendees.
  - q: I'm not in London, but this sounds cool! Can I come?
    a: This Field Day is specifically for London, but check out <a href="http://githubfieldday.com" class="text-purple">githubfieldday.com</a> for a Field Day in your area.
  - q: So I pre-registered to attend, what happens now?
    a: We'll get back to you soon! You'll receive an email, where you can claim your ticket.
  - q: How much does Field Day cost?
    a: Field Day is free to attend!
  - q: Will there be food?
    a: Yes! We'll have a light breakfast, and a full lunch and dinner! You will not go hungry.
  - q: Is there a Code of Conduct for this event?
    a: Yes! You can view it <a href="coc/" class="text-purple">here.</a>
  - q: Who is organizing Field Day?
    a: Field Day is organized by Campus Experts in London. <a href="//twitter.com/abdulajet" class="text-purple" target="_blank">Abdul</a>, <a href="//twitter.com/ruxi_ang" class="text-purple"  target="_blank">Ruxi</a>, and <a href="//twitter.com/wilhelmklopp" class="text-purple" target="_blank">Wil</a>.

# Build settings
markdown: kramdown

permalink: :categories/:title/
